### ISSUE TITLE
how to use sass file on development time 

### ISSUE THREAD

**Issue by gmchaturvedi1** [joshuacaron/generator-angular2-gulp-webpack#1]
as i am using saas it is processing correctioly on build but when node serer runiing it is not working can u please suggest and how can i activate live-reload

**Comment by joshuacaron** [comment]
Hi SASS should work with it. You either need to make sure that your generated css files end up in the src folder or say you were outputting the generated files into a dist folder you would need to add the following line into server.js:

```
app.use('/dist', express.static('dist'))
```

To get live reload working you should be able to use the express-livereload package on npm. I'll probably release a new version this weekend using that.

**Comment by joshuacaron** [comment]
I just released version 0.2.0 which has built in support for live reload.
